// -*- C++ -*-
// AID-GENERATED
// =========================================================================
// This class was generated by AID - Abstract Interface Definition          
// DO NOT MODIFY, but use the org.freehep.aid.Aid utility to regenerate it. 
// =========================================================================
#ifndef EVENT_LCFLAG_H
#define EVENT_LCFLAG_H 1

namespace EVENT {

/** Helper class to create and interpret the 32-bit flag word in LCCollections.
 *  Bits are defined in class LCIO.
 *
 * @see LCIO
 * @author gaede 
 * @version May 6, 2003
 */
class LCFlag {

public: 
    /// Destructor.
    virtual ~LCFlag() { /* nop */; }

    /** Returns true if bit at given index is set.
     */
    virtual bool bitSet(int index) const = 0;

    /**Returns the flag word.
     */
    virtual int getFlag() const = 0;

    /** Sets bit to 1.
     */
    virtual void setBit(int bit) = 0;

    /** Sets bit to 0.
     */
    virtual void unsetBit(int bit) = 0;
}; // class
} // namespace EVENT
#endif /* ifndef EVENT_LCFLAG_H */
