#!/bin/bash

dumpmctree-dot -h > /dev/null 2>&1 || echo "dumpmctree-dot executable not found. Make sure it's on PATH"; exit 1

if [ "${*}" = "-h" ] || [ "${*}" = "--help" ]; then
    dumpmctree-dot -h
    exit 0
fi

if dumpmctree-dot ${@}; then
    if [ -f dumpmctree.svg ]; then
        mv -f dumpmctree.svg dumpmctree.svg.bkp
    fi
    dot -Tsvg dumpmctree_tmp.dot > dumpmctree.svg 
    xdg-open dumpmctree.svg
fi
