// AID-GENERATED
// =========================================================================
// This class was generated by AID - Abstract Interface Definition          
// DO NOT MODIFY, but use the org.freehep.aid.Aid utility to regenerate it. 
// =========================================================================

package hep.lcio.event;


/** Helper class to create and interpret the 32-bit flag word in LCCollections.
 *  Bits are defined in class LCIO.
 *
 * @see LCIO
 * @author gaede 
 * @version May 6, 2003
 */
public interface LCFlag {

    /** Returns true if bit at given index is set.
     */
    public boolean bitSet(int index);

    /**Returns the flag word.
     */
    public int getFlag();

    /** Sets bit to 1.
     */
    public void setBit(int bit);

    /** Sets bit to 0.
     */
    public void unsetBit(int bit);
} // class or interface

