// AID-GENERATED
// =========================================================================
// This class was generated by AID - Abstract Interface Definition          
// DO NOT MODIFY, but use the org.freehep.aid.Aid utility to regenerate it. 
// =========================================================================

package hep.lcio.event;


/** Float vector used for user extensions.
 * The cpp implementation is a std::vector<float>
 * 
 * @author gaede 
 * @version Mar 12, 2003
 * @see LCObject
 */

public interface LCFloatVec extends LCObject {

    public float[] toArray();
} // class or interface

