// AID-GENERATED
// =========================================================================
// This class was generated by AID - Abstract Interface Definition          
// DO NOT MODIFY, but use the org.freehep.aid.Aid utility to regenerate it. 
// =========================================================================

package hep.lcio.event;


/** Int vector used for user extensions.
 * The cpp implementation is a std::vector<int>
 * 
 * @author gaede 
 * @version Aug 8, 2003
 * @see LCObject
 */
public interface LCIntVec extends LCObject {

    public int[] toArray();
} // class or interface

