// AID-GENERATED
// =========================================================================
// This class was generated by AID - Abstract Interface Definition          
// DO NOT MODIFY, but use the org.freehep.aid.Aid utility to regenerate it. 
// =========================================================================

package hep.lcio.event;


/** The generic object that is held in an LCCollection. 
 *  Every object stored in an LCCollection, i.e. in an LCEvent has to 
 *  implement this interface.
 * 
 * @author gaede 
 * @version Jun 7, 2003
 * fg 20040405 moved here from hep.lcio.data
 */
    
public interface LCObject extends Cloneable {

//           
//  public interface LCObject extends Cloneable {
//       
} // class or interface

