// AID-GENERATED
// =========================================================================
// This class was generated by AID - Abstract Interface Definition          
// DO NOT MODIFY, but use the org.freehep.aid.Aid utility to regenerate it. 
// =========================================================================

package hep.lcio.event;



import hep.lcio.exceptions.* ;
/** A single weighted relationship between two LCObjects. Stored in an LCCollection
 * like any other LCObject. Use inplementations of LCRelationNavigator to 
 * navigate the relation efficiently.
 * the types of the objects is decoded in the collection paramters 'RelationFromType'
 * and 'RelationToType'. In order to  store weights != 1. with the relation set the 
 * collection flag bit LCIO::LCREL_WEIGHTED, this is done automatically in 
 * UTIL::LCRelationNavigator if a weight != 1. exists.
 * 
 * @author gaede 
 * @version $Id: LCRelation.aid,v 1.7 2006-09-14 10:16:11 gaede Exp $
 * @see LCRelationNavigator
 */

public interface LCRelation extends LCObject {

    /** The 'from' object of the given relation. 
     */
    public LCObject getFrom();

    /** The 'to' object of the given relation. 
     */
    public LCObject getTo();

    /** The weight of the given relation - only if collection flag bit LCIO::LCREL_WEIGHTED is set. 
     */
    public float getWeight();
} // class or interface

