// AID-GENERATED
// =========================================================================
// This class was generated by AID - Abstract Interface Definition          
// DO NOT MODIFY, but use the org.freehep.aid.Aid utility to regenerate it. 
// =========================================================================

package hep.lcio.event;


/** Interface for the run header. 
 *
 * @author gaede
 * @version $Id: LCRunHeader.aid,v 1.8 2006-03-24 13:25:52 gaede Exp $
 */
public interface LCRunHeader extends LCObject {

    /** Returns the run number.
     */
    public int getRunNumber();

    /** Returns the name of the detector setup used in the simulation.
     */
    public String getDetectorName();

    /** Description of the simulation, physics channels etc.
     */		 
    public String getDescription();

    /** Returns the names of the active subdetectors
     *  used in the simulation.
     */ 
    public String[] getActiveSubdetectors();

    /** Parameters defined for this run.
     */
    public LCParameters getParameters();
} // class or interface

