// AID-GENERATED
// =========================================================================
// This class was generated by AID - Abstract Interface Definition          
// DO NOT MODIFY, but use the org.freehep.aid.Aid utility to regenerate it. 
// =========================================================================

package hep.lcio.event;


/** String vector used for user extensions.
 * The cpp implementation is a std::vector<string>
 * 
 * @author vogt
 * @version Jun 18, 2004
 * @see LCObject
 */
public interface LCStrVec extends LCObject {

    public String[] toArray();
} // class or interface

