// AID-GENERATED
// =========================================================================
// This class was generated by AID - Abstract Interface Definition          
// DO NOT MODIFY, but use the org.freehep.aid.Aid utility to regenerate it. 
// =========================================================================

package hep.lcio.event;


/** A generic simulated tracker hit. 
 * 
 * @author gaede
 * @version $Id: SimTrackerHit.aid,v 1.11 2010-06-17 12:28:59 engels Exp $
 */

public interface SimTrackerHit extends LCObject {

   /** Same name as in CalorimeterHit, even though there are no 'cells' in this case
     */
    public int getCellID0();

    /** Same name as in CalorimeterHit, even though there are no 'cells' in this case
     *  Optional, check/set flag(LCIO::THBIT_ID1)==1.
     */
    public int getCellID1();

    /** DEPRECATED: use @getCellID0()
     */
    public int getCellID();

    /** Returns the hit  position in [mm].	
     */
    public double[] getPosition();

    /** Returns  the dE/dx of the hit in [GeV].
     *  @deprecated
     *  @see getEDep()
     */
    public float getdEdx();

    /** The energy deposited on the hit [GeV]
     */
    public float getEDep();

    /** Returns the  time of the hit in [ns]. TO DO needs definition.
     */
    public float getTime();

    /** Returns the MC particle that caused the hit.
     *
     * @see MCParticle
     */
    public MCParticle getMCParticle();

    /** Returns the 3-momentum of the particle at the hits position in [GeV] - 
     * optional, only if bit LCIO::THBIT_MOMENTUM is set.	
     */ 
    public float[] getMomentum();

    /** The path length of the particle in the sensitive material that resulted in this hit.
     *  This is only stored together with momentum, i.e. if  LCIO::THBIT_MOMENTUM is set.
     */
    public float getPathLength();
} // class or interface

