// AID-GENERATED
// =========================================================================
// This class was generated by AID - Abstract Interface Definition          
// DO NOT MODIFY, but use the org.freehep.aid.Aid utility to regenerate it. 
// =========================================================================

package hep.lcio.event;


/** Deprecated. Please use TrackerRawData, TrackerData and TrackerPulse instead.
 *  A future version of LCIO will not support writing of TPCHit collections anymore.
 * 
 * @deprecated
 * @author gaede
 * @version $Id: TPCHit.aid,v 1.5 2006-03-24 13:25:52 gaede Exp $
 */

public interface TPCHit extends LCObject {

    /** Returns the detector specific cell id.
     */
    public int getCellID();

    /** Returns the  time of the hit.
     */
    public float getTime();

    /** Returns the integrated charge of the hit.
     */
    public float getCharge();

    /** Returns a quality flag for the hit.
     */
    public int getQuality();

    /** Return the number of raw data (32-bit) words stored for the hit.
     *  Check the flag word (bit TPCBIT_RAW) of the collection if raw data is
     *  stored at all.
     */
    public int getNRawDataWords();

    /** Return the raw data (32-bit) word at i.
     *  Check the flag word (bit TPCBIT_RAW) of the collection if raw data is
     *  stored at all.
     */
    public int getRawDataWord(int i);
} // class or interface

