// AID-GENERATED
// =========================================================================
// This class was generated by AID - Abstract Interface Definition          
// DO NOT MODIFY, but use the org.freehep.aid.Aid utility to regenerate it. 
// =========================================================================

package hep.lcio.event;


/** Tracker pulses as computed from  TrackerData objects or as directly measured by a specific
 *  subdetector. Typically TrackerHIts are created from TrackerPulses by some sort of clustering.
 *  @see TrackerRawData
 *  @see TrackerData
 * 
 * @author gaede
 * @version $Id: TrackerPulse.aid,v 1.5 2010-11-11 09:35:27 engels Exp $
 */

public interface TrackerPulse extends LCObject {

    /** Returns the first detector specific (geometrical) cell id.
     */
    public int getCellID0();

    /** Returns the second detector specific (geometrical) cell id. Optional, check/set 
     *  flag(LCIO::TRAWBIT_ID1)==1.
     */
    public int getCellID1();

    /** The time of the pulse - arbitrary units.
     */
    public float getTime();

    //The time error.
    //public float getTimeError() const ;	
     /** The integrated charge of the pulse - arbitrary units.
     */
    public float getCharge();

    // The charge error.
    //public float getChargeError() const ;	
    /** Covariance matrix of the charge (c) and time (t) measurements. Stored as lower triangle matrix, i.e.
     *  cov(c,c) , cov(t,c) , cov(t,t). Optional, check/set flag(LCIO::TRAWBIT_CM)==1.
     */
    public float[] getCovMatrix();

     /** The quality bit flag of the pulse - check/set collection parameters 
     *  TrackerPulseQualityNames and TrackerPulseQualityNamesValues.
     */
    public int getQuality();

    /** Optionally the TrackerData that has been used to create the pulse
     *  can be stored with the pulse - NULL if none. Check the quality bits for reason
     *  why the spectrum has been stored for the pulse.
     */
    public TrackerData getTrackerData();
} // class or interface

