// AID-GENERATED
// =========================================================================
// This class was generated by AID - Abstract Interface Definition          
// DO NOT MODIFY, but use the org.freehep.aid.Aid utility to regenerate it. 
// =========================================================================

package hep.lcio.event;


/** The Vertex class for LCIO. 
 *  <p>UNDER DEVELOPMENT!</p>
 *  see: <a href="http://forum.linearcollider.org/index.php?t=tree&goto=473">here</a><br>
 *
 *  <p>UNDER DEVELOPMENT!</p>
 *  
 * @author gaede, engels
 * @version $Id: Vertex.aid,v 1.3 2006-09-21 06:10:36 gaede Exp $
 */

public interface Vertex extends LCObject {

    /** Checks if the Vertex is the primary vertex of the event.
     *  Only one primary vertex per event is allowed
     */
    public boolean isPrimary();

    /** Type code for the algorithm that has been used to create the vertex - check/set the 
     *  collection parameters AlgorithmName and  AlgorithmType.
     */
    //public int getAlgorithmType() const ;
    public String getAlgorithmType();

     /** Chi squared of the vertex fit.
     */
    public float getChi2();

    /** Probability of the vertex fit.
     */
    public float getProbability();

    /** Position of the vertex
     */
    public float[] getPosition();

    /** Covariance matrix of the position (stored as lower triangle matrix, i.e. 
     *  cov(xx),cov(y,x),cov(y,y) ).
     */
    public float[] getCovMatrix();

    /** Additional parameters related to this vertex - check/set the collection
     *  parameter "VertexParameterNames" for the parameters' meaning.
     */
    public float[] getParameters();

    /** Returns Reconstructed Particle associated to the Vertex
     */
    public ReconstructedParticle getAssociatedParticle();
} // class or interface

