######################################################
#
# GNUmakefile to build the SIO library for LCIO
#
# @author Frank Gaede
# @date   Feb 11,2003
######################################################


SRC = ./src

INSTALL := $(shell pwd)/lib
export INSTALL

.PHONY: lib clean

lib:
	$(MAKE) -C $(SRC) lib


clean:
	$(MAKE) -C $(SRC) clean






