// AID-GENERATED
// =========================================================================
// This class was generated by AID - Abstract Interface Definition          
// DO NOT MODIFY, but use the org.freehep.aid.Aid utility to regenerate it. 
// =========================================================================

package hep.lcio.io;

import hep.lcio.event.LCRunHeader;

/** Listener for the occurence of LCRunHeader when reading a stream.
 * User classes should implement this interface for their analysis code 
 * and then register the listener with LCReader.
 * 
 * @author gaede 
 * @version Mar 11, 2003
 * @see LCRunHeader
 * @see LCReader
 */

public interface LCRunListener {

    /** Call back for processing an LCRunHeader. Access is 'read only'. 
     */
    public void processRunHeader(LCRunHeader rh);

    /** Call back for modifying an existing LCRunHeader. 
     */
    public void modifyRunHeader(LCRunHeader rh);

//     /** Call back for analyzing an LCRunHeader.
//      * @deprecated - use processRunHeader().
//      */
//     public void analyze(const  LCRunHeader* rh ) ;
//     /** Call back for updating an LCRunHeader.
//      * @deprecated - use modifyRunHeader().
//      */
//     public void update( LCRunHeader* rh ) ;
} // class or interface

