#!/bin/sh

ANT_HOME=$LCIO/tools
LOCALCLASSPATH=$ANT_HOME/freehep-buildtools.jar:$ANT_HOME/ant.jar:$ANT_HOME/ant-optional.jar:$ANT_HOME/jaxp.jar
LOCALCLASSPATH=$LOCALCLASSPATH:$ANT_HOME/parser.jar:$JDK_HOME/lib/tools.jar:$AIDA


# OS specific support for Cygwin 
cygwin=false;
case "`uname`" in
  CYGWIN*) cygwin=true ;;
esac
# For Cygwin, switch paths to Windows format before running java
if $cygwin; then
  ANT_HOME=`cygpath --windows "$ANT_HOME"`
  LOCALCLASSPATH=`cygpath --path --windows "$LOCALCLASSPATH"`
  java -cp "$LOCALCLASSPATH" -Dant.home="${ANT_HOME}%" org.apache.tools.ant.Main $@
else
  java -cp $LOCALCLASSPATH -Dant.home=$ANT_HOME% $ANT_OPTS org.apache.tools.ant.Main $@
fi

