
# --------- CMakeModules version ----------------
SET( ILCSOFT_CMAKE_MODULES_VERSION_MAJOR 1 )
SET( ILCSOFT_CMAKE_MODULES_VERSION_MINOR 11 )
SET( ILCSOFT_CMAKE_MODULES_VERSION_PATCH 0 )
SET( ILCSOFT_CMAKE_MODULES_VERSION_TWEAK 0 )
# -----------------------------------------------


SET( ILCSOFT_CMAKE_MODULES_VERSION ${ILCSOFT_CMAKE_MODULES_VERSION_MAJOR}.${ILCSOFT_CMAKE_MODULES_VERSION_MINOR}.${ILCSOFT_CMAKE_MODULES_VERSION_PATCH}.${ILCSOFT_CMAKE_MODULES_VERSION_TWEAK} )

GET_FILENAME_COMPONENT( ILCSOFT_CMAKE_MODULES_ROOT ${CMAKE_CURRENT_LIST_FILE} PATH )
IF( NOT ILCSOFT_CMAKE_MODULES_FIND_QUIETLY )
    MESSAGE( STATUS "Check for ILCSOFT_CMAKE_MODULES: ${ILCSOFT_CMAKE_MODULES_ROOT}" )
ENDIF()

INCLUDE( MacroCheckPackageVersion )
CHECK_PACKAGE_VERSION( ILCSOFT_CMAKE_MODULES ${ILCSOFT_CMAKE_MODULES_VERSION} )

SET( ILCSOFT_CMAKE_MODULES_VERSION_SUITABLE TRUE )
IF( PACKAGE_VERSION_UNSUITABLE )
     SET( ILCSOFT_CMAKE_MODULES_VERSION_SUITABLE FALSE )
ENDIF()

# ---------- final checking ---------------------------------------------------
INCLUDE( FindPackageHandleStandardArgs )
FIND_PACKAGE_HANDLE_STANDARD_ARGS( ILCSOFT_CMAKE_MODULES DEFAULT_MSG ILCSOFT_CMAKE_MODULES_VERSION_SUITABLE )

