name: key4hep

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: 16 4 * * 1

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        release: ["sw.hsf.org/key4hep",
                  "sw-nightlies.hsf.org/key4hep"]
        container_os: [el9]
        include:
          - release: "sw-nightlies.hsf.org/key4hep"
            container_os: ubuntu2404
    steps:
    - uses: actions/checkout@v3
      with:
        path: lcio
    - uses: cvmfs-contrib/github-action-cvmfs@v3
    - uses: aidasoft/run-lcg-view@v4
      with:
        container: ${{ matrix.container_os }}
        view-path: /cvmfs/${{ matrix.release }}
        run: |
          STARTDIR=$(pwd)
          cd $STARTDIR/lcio
          mkdir build install
          cd build
          cmake -DCMAKE_CXX_STANDARD=20 \
            -DBUILD_ROOTDICT=ON \
            -DCMAKE_CXX_FLAGS="-fdiagnostics-color=always -Werror " \
            -DCMAKE_INSTALL_PREFIX=../install \
            ..
          make -k
          ctest --output-on-failure
          make install
          echo "::group::Test downstream build"
          cd -
          export CMAKE_PREFIX_PATH=$PWD/install:$CMAKE_PREFIX_PATH
          cd tests/downstream-project-cmake-test
          mkdir build && cd build
          cmake .. -DCMAKE_CXX_STANDARD=20
          make -k
          echo "::group::Test python bindings"
          cd $STARTDIR/lcio
          cd install && source ../setup.sh
          cd ../
          rm -r $(ls | grep -v install)
          python $LCIO/python/examples/EventBuilder.py test.slcio 1
          python $LCIO/python/examples/readMCParticles.py test.slcio
